Remove the dependency on the readxl package
R-Lum/Luminescence pull request #270
Opened 2024-09-26 15:27 UTC by mcol

Note that the changes in the snapshot file for `.import_ThermochronometryData()` boil down to differences between `CLBR IR50` (before) and `CLBR_IR50` (now) because names were before taken from the XLS sheet names while now they are taken from the CSV file names, and when I generated them I used the underscore instead of a space. All the rest is perfectly reproduced.

Fixes #237.

2024-09-26 17:24 UTC, RLumSK requested changes
I have made some comments, its a little bit verbose, but we should give the user something.

2024-09-26 17:24 UTC, RLumSK commented on R/internals_Thermochronometry.R
My idea here was actually to have the function accepting either the current CSV file solution **and** a list of `data.frames`. With this we can drop an actual messages or ad something the manuscript that allows the user to use `readxl::read_excel()` to achieve the same thing without modifying the input format first. But perhaps his not a good, I guess I have to try the code. I will check this out.

I suggest we propose the following to the user if she/he tries to load an XLS file: 

```r
 .throw_error(
  {
    "XLS/XLSX format is not supported, use CSV instead.\n
    If you insist on using XLS/XLSX files, your input lines may read as follows:\n\n
    file_name <- '<your file>'
    file <- lapply(
     readxl::excel_sheets(file), function(x) {
       readxl::read_excel(file, sheet = x, .name_repair = 'unique_quiet')
     })\n"
    
  })
}
```

We then handle the rest of a list with data.frames (tibbles) comes in.

2024-09-27 06:59 UTC, mcol commented on R/internals_Thermochronometry.R
I've thought about this a bit more, and I think that such a message (even the short one I wrote) is unnecessary: this is an internal function, the check and the error message should be done in the caller. As an internal function we should trust that what we receive is what we expect.

2024-09-27 07:39 UTC, mcol commented on R/internals_Thermochronometry.R
As for accepting a list of data frames, we could do that, but it sounds cumbersome:
- Should the user just read an entire file into a single data frame, then we split it ourselves into header and body? It may be a bit messy to get the headers right for the body data frame
- Or should the user read the two parts separately? That puts quite some burden on the user, and it will make it hard to pass multiple input files to our function (a list of lists of data frames?).

I suggest to leave things as they are and revisit the whole scheme when we start working on the exported function.

2024-09-27 08:09 UTC, RLumSK commented on R/internals_Thermochronometry.R
OK, I see the point with the internal function and if at all, it should be coming in the function @feldsparlover and myself are currently working on. Means, agreed, just keep it as proposed. 

Regarding the splitting: Before posting, I had tried this yesterday and it work surprisingly well. However, in order to keep it simple for the internal function, let's shelf this until we have finished the other function with @feldsparlover, which will be exported.

2024-09-27 08:09 UTC, RLumSK approved these changes

2024-09-27 08:10 UTC, merged